/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/AcademicPath': RouteRecordInfo<'/AcademicPath', '/AcademicPath', Record<never, never>, Record<never, never>>,
    '/Connexion': RouteRecordInfo<'/Connexion', '/Connexion', Record<never, never>, Record<never, never>>,
    '/Contact': RouteRecordInfo<'/Contact', '/Contact', Record<never, never>, Record<never, never>>,
    '/ExperienceDetail': RouteRecordInfo<'/ExperienceDetail', '/ExperienceDetail', Record<never, never>, Record<never, never>>,
    '/Project': RouteRecordInfo<'/Project', '/Project', Record<never, never>, Record<never, never>>,
    '/ProjetDetail': RouteRecordInfo<'/ProjetDetail', '/ProjetDetail', Record<never, never>, Record<never, never>>,
    '/Skills': RouteRecordInfo<'/Skills', '/Skills', Record<never, never>, Record<never, never>>,
    '/Welcome': RouteRecordInfo<'/Welcome', '/Welcome', Record<never, never>, Record<never, never>>,
    '/WorkExperience': RouteRecordInfo<'/WorkExperience', '/WorkExperience', Record<never, never>, Record<never, never>>,
  }
}
